triad/urls.py
from django.urls import include, path
from .views import *


app_name = "triad"

urlpatterns = [
    path('', home, name='home'),
    path('potioningredients', ingredients, name='ingredients'),
    path('ingredients', ingredient_list, name='ingredient-list'),
    path('ingredients/<int:ingredient_id>', ingredient_details, name="ingredient"),
    path('ingredients/form', ingredient_form, name='new-ingredient-form'),
    path('ingredients/<int:ingredient_id>/form', ingredient_form, name='edit-ingredient-form'),

    path('spellwords', words, name='words'),
    path('words', word_list, name='word-list'),
    path('words/<int:word_id>', word_details, name="word"),
    path('words/form', word_form, name='new-word-form'),
    path('words/<int:word_id>/form', word_form, name='edit-word-form'),

    # path('logout', logout_user, name='logout'),
    # path('register', register_user, name='register'),
]

triadhtmx/urls.py
from django.contrib import admin
from django.urls import path, include
from triad.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('triad.urls')),
]

triad/models/artifact_materials.py
from django.db import models

class ArtifactMaterials(models.Model):
    artifact = models.ForeignKey("Artifact", on_delete=models.CASCADE)
    material = models.ForeignKey("Material", on_delete=models.CASCADE)
    class Meta:
        unique_together = ('artifact', 'material')

triad/models/artifacts.py
from django.db import models
from django.contrib.auth.models import User

class Artifact(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField()
    potency = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

triad/models/familiar_powers.py
from django.db import models

class FamiliarPowers(models.Model):
    power = models.ForeignKey("Power", on_delete=models.CASCADE)
    familiar = models.ForeignKey("Familiar", on_delete=models.CASCADE)
    class Meta:
        unique_together = ('power', 'familiar')

triad/models/familiars.py
from django.db import models

class Familiar(models.Model):
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    potency = models.IntegerField()
    date_created = models.DateTimeField()
    artifact = models.ForeignKey("Artifact", on_delete=models.CASCADE)
    spell = models.ForeignKey("Spell", on_delete=models.CASCADE)
    potion = models.ForeignKey("Potion", on_delete=models.CASCADE)

triad/models/ingredients.py
from django.db import models

class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    potency = models.IntegerField()
    type = models.ForeignKey("Type", on_delete=models.CASCADE)

triad/models/levels.py
from django.db import models

class Level(models.Model):
    name = models.CharField(max_length=255)
    number_of_wins = models.IntegerField()

triad/models/materials.py
from django.db import models

class Material(models.Model):
    material = models.CharField(max_length=255)
    potency = models.IntegerField()
    type = models.ForeignKey("Type", on_delete=models.CASCADE)

triad/models/potion_ingredients.py
from django.db import models

class PotionIngredients(models.Model):
    potion = models.ForeignKey("Potion", on_delete=models.CASCADE)
    ingredient = models.ForeignKey("Ingredient", on_delete=models.CASCADE)
    class Meta:
        unique_together = ('potion', 'ingredient')

triad/models/potions.py
from django.db import models
from django.contrib.auth.models import User

class Potion(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField()
    potency = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

triad/models/powers.py
from django.db import models

class Power(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    attack_strength = models.IntegerField()
    type = models.ForeignKey("Type", on_delete=models.CASCADE)

triad/models/spell_words.py
from django.db import models

class SpellWords(models.Model):
    spell = models.ForeignKey("Spell", on_delete=models.CASCADE)
    word = models.ForeignKey("Word", on_delete=models.CASCADE)
    class Meta:
        unique_together = ('spell', 'word')

triad/models/spells.py
from django.db import models
from django.contrib.auth.models import User

class Spell(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField()
    potency = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

triad/models/types.py
from django.db import models

class Type(models.Model):
    description = models.CharField(max_length=255)

triad/models/user_profile.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    background = models.CharField(max_length=255)
    sorceror_name = models.CharField(max_length=255)
    xp_level = models.ForeignKey("Level", on_delete=models.CASCADE)

triad/models/words.py
from django.db import models

class Word(models.Model):
    word = models.CharField(max_length=255)
    potency = models.IntegerField()
    type = models.ForeignKey("Type", on_delete=models.CASCADE)

triad/views/home.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

@require_http_methods(['GET'])
def home(request):
    return render(request, 'index.html')

triad/views/ingredients.py
from django.http import QueryDict
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from triad.models import Ingredient, Type

def list_all_ingredients(request):
    from itertools import groupby

    ingredients = Ingredient.objects.all().order_by("type", "-potency")

    grouped_ingredients = []
    for key, group in groupby(ingredients, lambda x: x.type.id):
        grouped_ingredients.append(list(group))

    return render(request, 'ingredients/partials/_list.html', {'ingredients': grouped_ingredients})

@require_http_methods(['GET'])
def ingredients(request):
    return render(request, 'ingredients/index.html')

@require_http_methods(['GET'])
def ingredient_form(request, ingredient_id=None):
    types = Type.objects.all()

    ingredient = None
    if ingredient_id is not None:
        ingredient = Ingredient.objects.get(pk=ingredient_id)

    return render(request, 'ingredients/partials/_form.html', {'ingredient': ingredient, 'types': types})

@require_http_methods(['GET', 'PUT', 'DELETE'])
def ingredient_details(request, ingredient_id):
    ingredient = Ingredient.objects.get(pk=ingredient_id)

    if request.method == 'GET':
        return render(request, 'ingredients/partials/_detail.html', {'ingredient': ingredient})

    elif request.method == 'DELETE':
        ingredient.delete()
        return list_all_ingredients(request)

    elif request.method == 'PUT':
        data = QueryDict(request.body)

        ingredient.name = data.get("name")
        ingredient.potency = data.get("potency")
        ingredient.type_id = data.get("type")
        ingredient.save()

        return render(request, 'ingredients/partials/_detail.html', {'ingredient': ingredient})

@require_http_methods(['GET', 'POST'])
def ingredient_list(request):
    if request.method == 'GET':
        return list_all_ingredients(request)

    elif request.method == 'POST':
        Ingredient.objects.create(
            name=request.POST.get('name'),
            potency=request.POST.get('potency'),
            type=Type.objects.get(pk=request.POST.get('type')),
        )
        return list_all_ingredients(request)

triad/views/words.py
from django.http import QueryDict
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from triad.models import Word, Type

def list_all_words(request):
    from itertools import groupby

    words = Word.objects.all().order_by("type", "-potency")

    grouped_words = []
    for key, group in groupby(words, lambda x: x.type.id):
        grouped_words.append(list(group))

    return render(request, 'words/partials/_list.html', {'words': grouped_words})

@require_http_methods(['GET'])
def words(request):
    return render(request, 'words/index.html')

@require_http_methods(['GET'])
def word_form(request, word_id=None):
    types = Type.objects.all()

    word = None
    if word_id is not None:
        word = Word.objects.get(pk=word_id)

    return render(request, 'words/partials/_form.html', {'word': word, 'types': types})

@require_http_methods(['GET', 'PUT', 'DELETE'])
def word_details(request, word_id):
    word = Word.objects.get(pk=word_id)

    if request.method == 'GET':
        return render(request, 'words/partials/_detail.html', {'word': word})

    elif request.method == 'DELETE':
        word.delete()
        return list_all_words(request)

    elif request.method == 'PUT':
        data = QueryDict(request.body)

        word.word = data.get("word")
        word.potency = data.get("potency")
        word.type_id = data.get("type")
        word.save()

        return render(request, 'words/partials/_detail.html', {'word': word})

@require_http_methods(['GET', 'POST'])
def word_list(request):
    if request.method == 'GET':
        return list_all_words(request)

    elif request.method == 'POST':
        Word.objects.create(
            word=request.POST.get('word'),
            potency=request.POST.get('potency'),
            type=Type.objects.get(pk=request.POST.get('type')),
        )
        return list_all_words(request)

triad/templates/words/partials/_detail.html
<section id="word-details" class="flex justify-center w-1/3 mt-12 flex-col">
  <div class="card card-normal w-full bg-base-100 shadow-xl">
    <figure>
      {% if word.type.description == "Fire" %}
      <img class="element_type max-w-40" src="https://clipartcraft.com/images/fire-clipart-cute-7.png" alt="Fire type" /></figure>
      {% endif %}
      {% if word.type.description == "Air" %}
      <img class="element_type max-w-40" src="https://img.favpng.com/5/9/17/air-computer-icons-classical-element-chemical-element-fire-png-favpng-DfVE86LAbWsaL9kcJ6z12YdD2.jpg" alt="Air type" /></figure>
      {% endif %}
      {% if word.type.description == "Water" %}
      <img class="element_type max-w-40" src="https://4.bp.blogspot.com/-faDgJn1qn4w/UD8-KBN515I/AAAAAAAABBw/G1P3HCHWXZ0/s1600/Water_Element_by_jadden.jpg" alt="Water type" /></figure>
      {% endif %}
      {% if word.type.description == "Earth" %}
      <img class="element_type max-w-40" src="https://www.lifecoachcode.com/wp-content/uploads/2014/08/Earth.jpg" alt="Earth type" /></figure>
      {% endif %}
      {% if word.type.description == "Arcane" %}
      <img class="element_type max-w-40" src="https://i.pinimg.com/originals/d4/28/92/d42892225ef160f81c006fd02d5996f5.jpg" alt="Arcane type" /></figure>
      {% endif %}
    <div class="card-body">
      <h2 class="card-title">{{ word.name }}</h2>
      <p>{{ word.type.description }} type of potency {{ word.potency }}</p>
      <div class="card-actions justify-end">
        <button hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
              hx-swap="innerHTML transition:true"
              hx-target="#dynamic-content"
              hx-delete="/words/{{word.id}}" class="btn btn-primary text-lg">Delete</button>
        <button hx-swap="innerHTML transition:true"
              hx-target="#dynamic-content"
              hx-get="/words/{{word.id}}/form"
              class="btn btn-secondary text-lg">Edit</button>
      </div>
    </div>
  </div>
</section>

triad/templates/words/partials/_form.html
<div hx-ext="response-targets" class="flex justify-center w-1/2 mt-12">
    {% if ingredient.id is not None %}
        <form class="w-full"
            hx-target="#dynamic-content"
            hx-put="{% url 'triad:ingredient' ingredient.id %}"
            hx-target-400="#badrequest"
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            hx-trigger="submit">
    {% else %}
        <form class="w-full" hx-post="/ingredients" hx-target="#dynamic-content" hx-target-400="#badrequest" hx-trigger="submit">
    {% endif %}
        {% csrf_token %}
        <fieldset class="flex items-center mb-4">
            <label class="block w-1/4 mr-2 text-left" for="name">Name: </label>
            <input class=" flex-1 input input-bordered rounded w-full" id="name" type="text" name="name" value="{{ ingredient.name }}">
        </fieldset>
        <fieldset class="flex items-center mb-4">
            <label class="block w-1/4 mr-2 text-left" for="potency">Potency: </label>
            <input class="flex-1 input input-bordered rounded w-full" id="potency" type="number" name="potency" value="{{ ingredient.potency }}">
        </fieldset>
        <fieldset class="flex items-center mb-4">
            <label class="block w-1/4 mr-2 text-left" for="type">Magical Type: </label>
            <select class="flex-1 input input-bordered rounded w-full" id="type" type="text" name="type">
                {% for type in types %}
                <option {% if type.id == ingredient.type_id %}selected{% endif %} value="{{ type.id }}">
                    {{ type.description }}</option>
                {% endfor %}
            </select>
        </fieldset>

        {% if ingredient.id is not None %}
            <button class="btn btn-secondary mx-auto">Update</button>
        {% else %}
            <button class="btn btn-secondary mx-auto">Create</button>
        {% endif %}
    </form>
</div>

triad/templates/words/partials/_list.html
<div class="flex flex-col w-1/2 mt-12">
{% for ingredient_type in ingredients %}
<h1>{{ ingredient_type.0.type.description }}</h1>
  <table class="table table-xl mx-auto">
    <tbody>
      {% for ingredient in ingredient_type %}
        <tr class="text-lg">
          <td class="w-4/5">
            <a class="link link-secondary" id="ingredient--{{ ingredient.id }}"
            hx-swap="innerHTML transition:true" hx-target="#dynamic-content"
            hx-get="{% url 'triad:ingredient' ingredient.id %}">{{ ingredient.name }}</a>
          </td>
          <td>{{ ingredient.potency }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endfor %}
</div>